name: Build and Deploy LaTeX PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      - name: Compile LaTeX to PDF
        run: pdflatex main.tex

      - name: Move PDF to publish folder
        run: |
          mkdir publish
          mv main.pdf publish/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
